# =============================================================================
# CORE INFRASTRUCTURE
# =============================================================================
# - AdGuard Home: DNS-level ad blocking
# - Traefik: Reverse proxy with automatic SSL
# =============================================================================

services:
  # ---------------------------------------------------------------------------
  # AdGuard Home - DNS Ad Blocker
  # ---------------------------------------------------------------------------
  # Access: http://server-ip:3000 (initial setup)
  # After setup: DNS server on port 53
  # ---------------------------------------------------------------------------
  adguard:
    image: adguard/adguardhome:latest
    container_name: adguard
    hostname: adguard
    restart: unless-stopped
    networks:
      - homeserver
    ports:
      - "${ADGUARD_DNS_PORT:-53}:53/tcp"
      - "${ADGUARD_DNS_PORT:-53}:53/udp"
      - "${ADGUARD_PORT:-3000}:3000/tcp"    # Web UI (initial setup)
      - "8053:80/tcp"                        # Web UI (after setup)
      - "853:853/tcp"                        # DNS-over-TLS
      - "3053:3000/udp"                      # DNS-over-QUIC
    volumes:
      - ${APPDATA_PATH}/adguard/work:/opt/adguardhome/work
      - ${APPDATA_PATH}/adguard/conf:/opt/adguardhome/conf
    environment:
      - TZ=${TZ}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adguard.rule=Host(`adguard.${DOMAIN}`)"
      - "traefik.http.routers.adguard.entrypoints=websecure"
      - "traefik.http.routers.adguard.tls.certresolver=cloudflare"
      - "traefik.http.services.adguard.loadbalancer.server.port=80"

  # ---------------------------------------------------------------------------
  # Traefik - Reverse Proxy
  # ---------------------------------------------------------------------------
  # Handles SSL termination and routing to all services
  # Dashboard: http://server-ip:8080
  # ---------------------------------------------------------------------------
  traefik:
    image: traefik:v3.0
    container_name: traefik
    hostname: traefik
    restart: unless-stopped
    networks:
      - homeserver
    ports:
      - "${TRAEFIK_HTTP_PORT:-80}:80"
      - "${TRAEFIK_HTTPS_PORT:-443}:443"
      - "8080:8080"                          # Dashboard
    environment:
      - TZ=${TZ}
      - CF_API_TOKEN=${CF_API_TOKEN}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${APPDATA_PATH}/traefik:/etc/traefik
      - ${APPDATA_PATH}/traefik/acme.json:/acme.json
    command:
      # API and Dashboard
      - "--api.dashboard=true"
      - "--api.insecure=true"
      # Docker provider
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=homeserver"
      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      # Let's Encrypt with Cloudflare DNS challenge
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.email=admin@${DOMAIN}"
      - "--certificatesresolvers.cloudflare.acme.storage=/acme.json"
      # Logging
      - "--log.level=INFO"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik.service=api@internal"
